### ISSUE TITLE
Rule fix does not follow code indentation

### ISSUE THREAD

**Issue by practicalgnome** [num13ru/eslint-plugin-change-detection-strategy#7]
When fix applied it adds line with wrong indentation:

![image](https://github.com/num13ru/eslint-plugin-change-detection-strategy/assets/28387782/f76408ef-9b9b-4b20-aed7-075c9f2c20bc)

**Comment by practicalgnome** [comment]
Can I work on that?

**Comment by num13ru** [comment]
Yeah feel free

**Comment by num13ru** [comment]
Thanks for the #8
